server:
  port: 8888
spring:
  application:
    name: talenthub-config-server # Tên của Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PhuNguyen12345/talenthub-config-repo # Địa chỉ repository GitHub của bạn
          search-paths: 
            - talenthub-config-repo # Thư mục chứa file cấu hình trong repository

  