server:
  port: 8083
spring:
  application:
    name: application-service
  datasource:
    url: jdbc:postgresql://localhost:5432/talenthub_application_db
    username: admin
    password: Nguyenanphu2005@
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health, info